// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Markets_Namespace.Data.Models
{
    public partial class Markets_DBContext : DbContext
    {
        public Markets_DBContext()
        {
        }

        public Markets_DBContext(DbContextOptions<Markets_DBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Market> Market { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Market>(entity =>
            {
                entity.ToTable("market");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.GlCode)
                    .HasColumnName("gl_code")
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Nickname)
                    .HasColumnName("nickname")
                    .HasMaxLength(30)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}